[features]
seeds = false
skip-lint = false
[programs.localnet]
#myepicproject = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
myepicproject = "dztQKNs4Fq7QDbGoSxFyygcuUuGy6wTCryv2GmEPqRx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/aenikata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.js"
